version: 2
formats: [htmlzip]
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  commands:
    - python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/htmlzip 
sphinx:
  configuration: docs/conf.py
  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
  builder: "html"
python:
  install:
  - requirements: docs/requirements.txt
